import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import prisma from "../../lib/prisma";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { Header } from "../../components/header";
import { useMutation } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  allUsers,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const { mutate } = useMutation(["test"], async () => fetch("/api/hello"));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main className={styles.main}>
        <h1>ALL USER</h1>
        <button
          onClick={() => {
            mutate();
          }}
        >
          TEST FETCH
        </button>
        <ul>
          {allUsers.map((user) => (
            <li key={user.id}>
              <span>{user.name}</span>
              <span>{user.email}</span>
              <span>{user.posts[0]?.title}</span>
              {/* <span>{user.updatedAt.toDateString()}</span> */}
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const allUsers = await prisma.user.findMany({
    select: {
      name: true,
      email: true,
      id: true,
      posts: {
        select: {
          title: true,
        },
      },
    },
  });
  return {
    props: { allUsers },
  };
}
